# Generated by Django 4.0.10 on 2023-02-26 17:21

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(help_text='Escriba la respuesta de la pregunta', verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, help_text='No es necesario eliminar una respuesta, basta con desactivar para que ya no se muestre en la app', verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.PositiveIntegerField(help_text='Es el número de la pregunta, también sirve para ordenarlo de menor a mayor', verbose_name='N°')),
                ('description', models.TextField(help_text='Escriba el enunciado de la pregunta', verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, help_text='No es necesario eliminar una pregunta, basta con desactivar para que ya no se muestre en la app', verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['number'],
            },
        ),
    ]
