# Generated by Django 4.0.10 on 2023-02-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Exam',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='test',
            new_name='exam',
        ),
    ]
