# Generated by Django 4.0.10 on 2023-02-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Exam',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='test',
            new_name='exam',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer', to='tests.question', verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='tests.student', verbose_name='Estudiante'),
        ),
    ]
